### ISSUE TITLE
Feature: Add a hotkey for clearing filters and possibly a display of active filters

### ISSUE THREAD

**Issue by KerfuffleV2** [8008fondler/riftwiz#2]
Hey, thanks for your work on this! It's a great resource.

One possible small improvement would be to make it possible to clear all filters with a hotkey. Something like `esc`, `space`, `backspace` would work well. It seems like there's also room  for a small help section over where the spell types are listed.

It might also be good to just add a small status display for what filters are selected. Just something very simple like `Filters: ae` or whatever would work. I know it does recolor the school name like the actual game but this also hides the hotkey and isn't collected in one place.

Would you accept a pull request with those changes? If so, I might put my money where my mouth is and implement it myself.

These are small improvements and the tool is very useful without any changes. Appreciate you making this available!

**Comment by 8008fondler** [comment]
"Escape" button now clears the selected schools.

You should probably use/comment [this fork](https://github.com/carlank/riftwiz/)  since it is a bit ahead: it has text search + the creator is in process of adding build calculator functionality.

**Comment by KerfuffleV2** [comment]
Thanks for the reply. I didn't know about the other fork.
